version: '3'
services:

  php7.4:
    container_name: php7.4
    restart: always
    image: php7.4-apache-exp
    build:
      dockerfile: php7.4-apache-exp.dockerfile
      context: ./docker-files/
      args:
        - INSTALL_GD=${INSTALL_GD}
        - INSTALL_FTP=${INSTALL_FTP}
        - INSTALL_MBSTRING=${INSTALL_MBSTRING}
        - INSTALL_PDO_MYSQL=${INSTALL_PDO_MYSQL}
        - INSTALL_PDO_POSTGRESQL=${INSTALL_PDO_POSTGRESQL}
        - INSTALL_OCI8_PDO_ORACLE=${INSTALL_OCI8_PDO_ORACLE}
        - INSTALL_MYSQLI=${INSTALL_MYSQLI}
        - INSTALL_BCMATH=${INSTALL_BCMATH}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - INSTALL_TOKENIZER=${INSTALL_TOKENIZER}
        - INSTALL_JSON_XML=${INSTALL_JSON_XML}
        - INSTALL_COMPOSER=${INSTALL_COMPOSER}
        - INSTALL_CRON=${INSTALL_CRON}
        - INSTALL_NPM=${INSTALL_NPM}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APPLICATION}:/var/www/html/
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      #- ${APACHE_SSL_PATH}:/etc/ssl/private
      - ${TIMEZONE}:/etc/timezone:ro
      - ${LOCALTIME}:/etc/localtime:ro
    links:
      - mysql
    networks:
      - docker-network
    depends_on:
      - mysql

  php5.6:
      container_name: php5.6
      restart: always
      image: php5.6-apache-exp
      build:
          dockerfile: php5.6-apache-exp.dockerfile
          context: ./docker-files
      ports:
          - "${APACHE_HOST_HTTP_OLD_PORT}:80"
      volumes:
          - ${APPLICATION_OLD}:/var/www/html/5.6
          - ${TIMEZONE}:/etc/timezone:ro
          - ${LOCALTIME}:/etc/localtime:ro
      links:
          - mysql
      networks:
          - docker-network
      depends_on:
          - mysql

  mysql:
    image: mysql:8
    container_name: mysql8
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_CONF}:/etc/mysql/conf.d
      - ${MYSQL_LOG}:/var/log/mysql
      - ${TIMEZONE}:/etc/timezone:ro
      - ${LOCALTIME}:/etc/localtime:ro
    environment:
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=America/Sao_Paulo
    networks:
      - docker-network

networks:
    docker-network:
        driver: bridge
